export const guestList = [
  {id: 0, table: 1, name: "Joseph M Jahja", meal: "Beef Short Rib"},
  {id: 1, table: 1, name: "Jessica Wijaya", meal: "Beef Short Rib"},
  {id: 2, table: 1, name: "Elizabeth S Melinda", meal: "Grilled Salmon Fillet"},
  {id: 3, table: 1, name: "Wahyu Hidajati", meal: "Beef Short Rib"},
  {id: 4, table: 1, name: "Cornelia Maxine", meal: "Grilled Salmon Fillet"},
  {id: 5, table: 1, name: "Constantine Alexander Soelaiman", meal: "Grilled Salmon Fillet"},
  {id: 6, table: 1, name: "Kartika Dewi", meal: "Beef Short Rib"},
  {id: 7, table: 1, name: "Rosalina Christiani", meal: "Beef Short Rib"},
  {id: 8, table: 1, name: "Richard Bradley", meal: "Beef Short Rib"},
  {id: 9, table: 1, name: "Robert Matusik", meal: "Beef Short Rib"},
  {id: 10, table: 1, name: "Adelia Yolanda", meal: "Beef Short Rib"},

  {id: 11, table: 2, name: "Yudi chandra", meal: "Beef Short Rib"},
  {id: 12, table: 2, name: "Hera susanto", meal: "Beef Short Rib"},
  {id: 13, table: 2, name: "Xuan Yao", meal: "Beef Short Rib"},
  {id: 14, table: 2, name: "Lidya Susanto", meal: "Beef Short Rib"},
  {id: 15, table: 2, name: "Donna Rota", meal: "Grilled Salmon Fillet"},
  {id: 16, table: 2, name: "Allen Rota", meal: "Beef Short Rib"},
  {id: 17, table: 2, name: "Ferdy Tjahjadi", meal: "Beef Short Rib"},
  {id: 18, table: 2, name: "Mailina Kurniawan", meal: "Beef Short Rib"},
  {id: 19, table: 2, name: "Venlyna Phang", meal: "Beef Short Rib"},
  {id: 20, table: 2, name: "Hermanto Hioe", meal: "Beef Short Rib"},

  {id: 21, table: 3, name: "Yanti Ekasalim", meal: "Grilled Salmon Fillet"},
  {id: 22, table: 3, name: "Dewi Ekasalim", meal: "Beef Short Rib"},
  {id: 23, table: 3, name: "Yenny Ekasalim", meal: "Grilled Salmon Fillet"},
  {id: 24, table: 3, name: "Henny Ekasalim", meal: "Grilled Salmon Fillet"},
  {id: 25, table: 3, name: "Lily Suryanto", meal: "Grilled Salmon Fillet"},
  {id: 26, table: 3, name: "Eddy Ekasalim", meal: "Beef Short Rib"},
  {id: 27, table: 3, name: "Sehan Ekasalim", meal: "Beef Short Rib"},
  {id: 28, table: 3, name: "Flora Susanto", meal: "Grilled Salmon Fillet"},
  {id: 29, table: 3, name: "Dewi Amelia", meal: "Grilled Salmon Fillet"},
  {id: 30, table: 3, name: "Indri Simanhadi", meal: "Beef Short Rib"},

  {id: 31, table: 4, name: "Joshua Salamun", meal: "Grilled Salmon Fillet"},
  {id: 32, table: 4, name: "Nadia Tan", meal: "Beef Short Rib"},
  {id: 33, table: 4, name: "Camellia Tan", meal: "Beef Short Rib"},
  {id: 34, table: 4, name: "Edwin Chan", meal: "Beef Short Rib"},
  {id: 37, table: 4, name: "Angela Susilo", meal: "Beef Short Rib"},
  {id: 38, table: 4, name: "Randy Yuwono", meal: "Grilled Salmon Fillet"},
  {id: 39, table: 4, name: "Adrian Hartanto", meal: "Beef Short Rib"},
  {id: 40, table: 4, name: "Michael Chow", meal: "Beef Short Rib"},
  {id: 41, table: 4, name: "Nanda Kuswanto", meal: "Beef Short Rib"},
  {id: 42, table: 4, name: "Maureen Usman", meal: "Beef Short Rib"},

  {id: 43, table: 5, name: "Stefany Jaya", meal: "Beef Short Rib"},
  {id: 44, table: 5, name: "Geoffrey Rota", meal: "Beef Short Rib"},
  {id: 45, table: 5, name: "Genice Chandra", meal: "Beef Short Rib"},
  {id: 46, table: 5, name: "Louis Zhang", meal: "Beef Short Rib"},
  {id: 47, table: 5, name: "Timothy Simanhadi", meal: "Beef Short Rib"},
  {id: 48, table: 5, name: "Joshua Ekasalim", meal: "Beef Short Rib"},
  {id: 49, table: 5, name: "Fernando Ng", meal: "Grilled Salmon Fillet"},
  {id: 50, table: 5, name: "Otto Priadi", meal: "Beef Short Rib"},

  {id: 51, table: 6, name: "Jessica Samiri", meal: "Beef Short Rib"},
  {id: 52, table: 6, name: "Shierly Xu", meal: "Grilled Salmon Fillet"},
  {id: 53, table: 6, name: "Christopher", meal: "Beef Short Rib"},
  {id: 54, table: 6, name: "Sinclair Kenrick", meal: "Beef Short Rib"},
  {id: 55, table: 6, name: "Gracia Sharon", meal: "Grilled Salmon Fillet"},
  {id: 56, table: 6, name: "Lisandra legawa", meal: "Grilled Salmon Fillet"},
  {id: 57, table: 6, name: "Jackson Michaels Widjaya", meal: ""},
  {id: 58, table: 6, name: "Clyve Widjaya", meal: "Beef Short Rib"},
  {id: 59, table: 6, name: "Billy Xu", meal: "Beef Short Rib"},
  {id: 60, table: 6, name: "Samuel Priyatna", meal: "Beef Short Rib"},

  {id: 61, table: 7, name: "Haris", meal: "Beef Short Rib"},
  {id: 62, table: 7, name: "Adrian Vincent", meal: "Beef Short Rib"},
  {id: 63, table: 7, name: "Gavin Sayuto", meal: "Beef Short Rib"},
  {id: 64, table: 7, name: "Carlos Agena", meal: "Beef Short Rib"},
  {id: 65, table: 7, name: "Jeff Soo", meal: "Beef Short Rib"},
  {id: 66, table: 7, name: "Lucia Chonn", meal: "Grilled Salmon Fillet"},
  {id: 67, table: 7, name: "Patricia de Paula e Freitas", meal: "Herb Roasted Chicken"},
  {id: 68, table: 7, name: "Gabriela de Paula e Freitas Nunes", meal: "Kid's Meal"},
  {id: 69, table: 7, name: "Wlademir Nunes", meal: "Grilled Salmon Fillet"},
  {id: 70, table: 7, name: "Maedal", meal: "Grilled Salmon Fillet"},
];